require("globals")
require("options")
require("keymaps")
require("autocmds")
require("winbar")

require("plugin.packer")
require("plugin.palette")
require("plugin.telescope")
require("plugin.whichkey")
require("plugin.neo-tree")
require("plugin.autopairs")
require("plugin.bufferline")
require("plugin.lualine")
require("plugin.devicons")
require("plugin.nvim-cmp")
require("plugin.treesitter")
require("plugin.comment")
require("plugin.nvim-ufo")
-- require("plugin.null-ls") -- not working
require("plugin.surround")

require("plugin.lsp-config.settings")
require("plugin.lsp-config.servers")
