require("dashboard").setup({
	theme = "doom",
	hide = {
		tabline = false,
		statusline = true,
	},
	config = {
		header = {
			"                                                                        ",
			"                                                                        ",
			"                                                                        ",
			"    ██████   █████                   █████   █████  ███                 ",
			"   ░░██████ ░░███                   ░░███   ░░███  ░░░                  ",
			"    ░███░███ ░███   ██████   ██████  ░███    ░███  ████  █████████████  ",
			"    ░███░░███░███  ███░░███ ███░░███ ░███    ░███ ░░███ ░░███░░███░░███ ",
			"    ░███ ░░██████ ░███████ ░███ ░███ ░░███   ███   ░███  ░███ ░███ ░███ ",
			"    ░███  ░░█████ ░███░░░  ░███ ░███  ░░░█████░    ░███  ░███ ░███ ░███ ",
			"    █████  ░░█████░░██████ ░░██████     ░░███      █████ █████░███ █████",
			"   ░░░░░    ░░░░░  ░░░░░░   ░░░░░░       ░░░      ░░░░░ ░░░░░ ░░░ ░░░░░ ",
			"                                                                        ",
			"                                                                        ",
			"       ────────────────────────────────────────────────────────────     ",
			"                                                                        ",
		},
		center = {
			{
				icon = "󰻭   ",
				icon_hl = "Color1",
				desc = "New File                            ",
				key = "n",
				key_hl = "string",
				keymap = "Space f n ",
				action = "enew",
			},
			{
				icon = "󰱽   ",
				icon_hl = "Color2",
				desc = "Find Files",
				key = "f",
				key_hl = "String",
				keymap = "Space f f ",
				action = "Telescope find_files",
			},
			{
				icon = "󱋢   ",
				icon_hl = "Color3",
				desc = "Recent Files",
				key = "r",
				keymap = "Space f r ",
				key_hl = "String",
				action = "Telescope oldfiles",
			},
			{
				icon = "󱁼   ",
				icon_hl = "Color4",
				desc = "Dotfiles",
				key = "d",
				keymap = "Space o d ",
				key_hl = "String",
				action = "WhichKey <leader>od",
			},
			{
				icon = "󰙅   ",
				icon_hl = "Color5",
				desc = "Explore",
				key = "e",
				keymap = "Space o e ",
				key_hl = "String",
				action = "Neotree float",
			},
			{
				icon = "󰅚   ",
				icon_hl = "Color6",
				desc = "Quit",
				key_hl = "Hide",
				action = "q!",
			},
		},
		footer = { vim.fn.matchstr(vim.fn.execute("version"), [[NVIM v\zs[^\n]*]]) },
	},
})
