ky.ui.icons = {
  mini = {
    default = {
      directory = { glyph = '󰉋', hl = 'Directory' },
      file = { glyph = '', hl = 'MiniIconsBlue' },
    },

    directory = {
      ui = { glyph = '󱞊', hl = 'MiniIconsPurple' },
      public = { glyph = '󱞊', hl = 'MiniIconsBlue' },
      config = { glyph = '󱁿', hl = 'MiniIconsYellow' },
      ['.avante_chat_history'] = { glyph = '', hl = 'MiniIconsGrey' },
    },

    file = {
      ['.gitignore'] = { glyph = '', hl = 'MiniIconsGrey' },
      ['pnpm-lock.yaml'] = { glyph = '', hl = 'MiniIconsGreen' },
      ['README.md'] = { glyph = '', hl = 'MiniIconsBlue' },
      ['init.lua'] = { glyph = '', hl = 'MiniIconsGreen' },
      ['tailwind.config.ts'] = { glyph = '󱏿', hl = 'MiniIconsBlue' },
      ['kitty.conf'] = { glyph = '󰄛', hl = 'MiniIconsGreen' },
      ['.env'] = { glyph = '', hl = 'MiniIconsGrey' },
      ['.env.local'] = { glyph = '', hl = 'MiniIconsGrey' },
    },

    filetype = {
      bash = { glyph = '', hl = 'MiniIconsGreen' },
      csv = { glyph = '', hl = 'MiniIconsGreen' },
      pdf = { glyph = '', hl = 'MiniIconsGreen' },
      sh = { glyph = '', hl = 'MiniIconsGreen' },
      xmodmap = { glyph = '', hl = 'MiniIconsCyan' },
      xinitrc = { glyph = '󰨇', hl = 'MiniIconsBlue' },
      python = { glyph = '', hl = 'MiniIconsYellow' },
      zsh = { glyph = '', hl = 'MiniIconsGreen' },
    },

    extension = {
      ['js'] = { glyph = '', hl = 'MiniIconsYellow' },
      ['ts'] = { glyph = '', hl = 'MiniIconsBlue' },
      ['tsx'] = { glyph = '󰜈', hl = 'MiniIconsBlue' },
      ['norg'] = { glyph = '󱇨', hl = 'MiniIconsPurple' },
      ['jpg'] = { glyph = '', hl = 'MiniIconsBlue' },
      ['png'] = { glyph = '', hl = 'MiniIconsGreen' },
      ['mp4'] = { glyph = '', hl = 'MiniIconsPurple' },
      ['ttf'] = { glyph = '', hl = 'MiniIconsPurple' },
      ['zip'] = { glyph = '', hl = 'MiniIconsYellow' },
      ['md'] = { glyph = '', hl = 'MiniIconsBlue' },
    },
  },
  symbol_kinds = {
    File = ' ',
    Module = ' ',
    Namespace = ' ',
    Package = ' ',
    Class = ' ',
    Method = ' ',
    Property = ' ',
    Field = ' ',
    Constructor = ' ',
    Enum = ' ',
    Interface = ' ',
    Function = ' ',
    Variable = ' ',
    Constant = ' ',
    String = ' ',
    Number = ' ',
    Boolean = ' ',
    Array = ' ',
    Object = ' ',
    Key = ' ',
    Null = ' ',
    EnumMember = ' ',
    Struct = ' ',
    Event = ' ',
    Operator = ' ',
    TypeParameter = ' ',
  },

  completion = {
    Text = ' 󰦨 ',
    Method = ' 󰡱 ',
    Function = ' 󰊕 ',
    Constructor = ' 󰒓',
    Field = ' 󱈤 ',
    Variable = ' 󰦨 ',
    Property = ' 󰖷',
    Class = ' 󱡠',
    Interface = ' 󱡠',
    Struct = ' 󱡠',
    Module = ' 󰏗 ',
    Unit = ' 󰪚',
    Value = ' 󰦨 ',
    Enum = ' 󰦨 ',
    EnumMember = ' 󰦨 ',
    Keyword = '  ',
    Constant = ' 󰏿 ',
    Snippet = ' 󰭸 ',
    Color = ' 󰏘 ',
    File = ' 󰈔',
    Reference = ' 󰬲',
    Folder = ' 󰉋 ',
    Event = ' 󱐋',
    Operator = ' 󰪚 ',
    TypeParameter = ' 󰬛 ',
  },

  editor = {
    file = ' ',
    book = ' ',
    book_alt = '',
    error = ' ',
    warning = ' ',
    hint = ' ',
    info = ' ',
    chevron = '  ',
    keyboard = '',
    git_branch = '󰘬 ',
    indent = '│',
  },

  -- Diagnostics icons
  diagnostics = {
    ERROR = '',
    WARN = '',
    HINT = '',
    INFO = '',
  },

  -- Neotree specific icons
  neo_tree = {
    folders = { open = '󰷏', closed = '', empty = '' },
    indent_marker = '│',
    last_indent_marker = '└ ',
    warn = '  ',
    info = '  ',
    hint = '  ',
    error = '  ',
    git = {
      add = '   ',
      modified = '  ',
      deleted = '󰖭  ',
      ignore = '  ',
      rename = '  ',
      untracked = '  ',
      ignored = '  ',
      unstaged = '󰄱  ',
      staged = '  ',
      conflict = '  ',
      diff = '  ',
      repo = '  ',
      logo = '󰊢  ',
      branch = '󰘬  ',
    },
  },

  separators = {
    left_thin_block = '▏',
    right_thin_block = '▕',
  },

  lsp = {
    error = ' ',
    warn = ' ',
    info = ' ',
    hint = ' ',
  },

  git = {
    add = ' ', --    
    mod = ' ', --  
    remove = ' ', --    
    ignore = '',
    rename = '',
    untracked = '',
    ignored = '',
    unstaged = '󰄱',
    staged = '',
    conflict = '',
    diff = '',
    repo = '',
    logo = '󰊢',
    branch = '󰘬',
  },

  documents = {
    file = '',
    files = '',
    folder = '',
    open_folder = '',
  },

  misc = {
    fzf = '',
    readonly = ' ',
    none = '',
    pointer = '➤',
    search = ' ',
    git = '',
    vertical_bar = '▍',
    plus = '',
    ellipsis = '…',
    up = '⇡',
    down = '⇣',
    -- line = '', -- 'ℓ'
    line = 'Ξ', -- 'ℓ'
    indent = 'Ξ',
    tab = '⇥',
    bug = '', --  '󰠭'
    question = '',
    clock = '',
    lock = '',
    shaded_lock = '',
    circle = '',
    project = '',
    dashboard = '',
    history = '󰄉',
    comment = '󰅺',
    robot = '󰚩',
    lightbulb = '󰌵',
    code = '',
    telescope = '',
    gear = '',
    package = '',
    list = '',
    sign_in = '',
    check = '󰄬',
    fire = '',
    note = '󰎞',
    bookmark = '',
    pencil = '', -- '󰏫',
    tools = '',
    arrow_right = '',
    caret_right = '',
    chevron_right = '',
    double_chevron_right = '»',
    table = '',
    calendar = '',
    block = '▌',
    separator = ' ',
  },
}
