return {
  ai = {
    openai_api_key = os.getenv('OPENAI_API_KEY'),
    gpt_model = 'gpt-3.5-turbo-0613',
  },

  italic = {
    strings = false,
    comments = false,
    operators = false,
    folds = false,
  },

  hex_palettes = {
    {
      name = 'lush-green',
      background_mode = 'dark',
      background = '#0f1a0e',
      foreground = '#b8c5b4',
      accents = {
        '#419544',
        '#76a63f',
        '#aebb30',
        '#008074',
        '#00bcd4',
        '#3f51b5',
        '#9c27b0',
      },
    },
    {
      name = 'half-moon (pink)',
      background_mode = 'dark',
      background = '#1c1c1c',
      foreground = '#f7f7f7',
      accents = {
        '#ff6ac1',
        '#ff8ac1',
        '#ffa9c1',
        '#ffc8c1',
        '#ffe7c1',
        '#fffbf7',
        '#fffbf7',
      },
    },
    {
      name = 'full-moon (yellow)',
      background_mode = 'dark',
      background = '#0c0c0c',
      foreground = '#f2f2f2',
      accents = {
        '#f7e8a6',
        '#b3b3b3',
        '#e8e8e8',
        '#d9d9d9',
        '#c0c0c0',
        '#a6a6a6',
        '#8c8c8c',
      },
    },
    {
      name = 'full-moon (purple)',
      background_mode = 'dark',
      background = '#0c0c0c',
      foreground = '#dcdcdc',
      accents = {
        '#a45ee5',
        '#7a7ae5',
        '#5e7ae5',
        '#50c3b4',
        '#50c38b',
        '#e5d45e',
        '#e57a5e',
      },
    },
    {
      name = 'blood-orange',
      background_mode = 'dark',
      background = '#0e0800',
      foreground = '#ffcc99',
      accents = {
        '#ff6633',
        '#ff9966',
        '#ff3300',
        '#ff9933',
        '#ff6600',
        '#ffcc66',
        '#ff9900',
      },
    },

    {
      name = 'pastel-cyber-scape',
      background_mode = 'dark',
      background = '#0f0f0f',
      foreground = '#f2f2f2',
      accents = {
        '#ff6ac1',
        '#6ac1ff',
        '#ff9d6a',
        '#5ad9a4',
        '#c16aff',
        '#a4d95a',
        '#ff6ac1',
      },
    },
    {
      name = 'time-machine',
      background_mode = 'dark',
      background = '#1d1f21',
      foreground = '#cccccc',
      accents = {
        '#81a2be',
        '#b294bb',
        '#de935f',
        '#75a29c',
        '#f0c674',
        '#9aa158',
        '#a3685a',
      },
    },
    {
      name = 'zen-night',
      background_mode = 'dark',
      background = '#0f111a',
      foreground = '#d8dee9',
      accents = {
        '#c792ea',
        '#89ddff',
        '#a6c578',
        '#82aaff',
        '#6dada7',
        '#ffcb6b',
        '#ff5370',
      },
    },
    {
      name = 'gray-planet',
      background_mode = 'dark',
      background = '#333333',
      foreground = '#cccccc',
      accents = {
        '#999999',
        '#999999',
        '#cccccc',
        '#999999',
        '#bbbbbb',
        '#999999',
        '#aaaaaa',
      },
    },
    {
      name = 'pitch blue',
      background_mode = 'dark',
      background = '#0a0e14',
      foreground = '#cfd8dc',
      accents = {
        '#00b0ff',
        '#00e5ff',
        '#00d9ad',
        '#00d95e',
        '#00d900',
        '#5dd900',
        '#add900',
      },
    },

    {
      name = 'magic-lavender',
      background_mode = 'dark',
      background = '#17141a',
      foreground = '#f3ecff',
      accents = {
        '#c7aff4',
        '#99afcb',
        '#ffb0d7',
        '#bbd9fd',
        '#e0b4ea',
        '#ffccf9',
        '#ffcded',
      },
    },

    {
      name = 'her-theme',
      background_mode = 'dark',
      background = '#1e1e1e',
      foreground = '#d4d4d4',
      accents = {
        '#ff6ac1',
        '#78dce8',
        '#90bb64',
        '#e8d478',
        '#b45bcf',
        '#6ac1ff',
        '#ff6a6a',
      },
    },
    {
      name = 'forest-contrast',
      background_mode = 'dark',
      background = '#0d1f1a',
      foreground = '#c3c8bf',
      accents = {
        '#3f854d',
        '#5d9f79',
        '#8bb896',
        '#f0e6c8',
        '#f7c873',
        '#f4a261',
        '#e76f51',
      },
    },

    {
      name = 'north-star',
      background_mode = 'dark',
      background = '#0c0f1c',
      foreground = '#d8dde8',
      accents = {
        '#ff6ac1',
        '#6ac1ff',
        '#a4d95a',
        '#ffaa6a',
        '#5ad991',
        '#aa6aff',
        '#ffaa6a',
      },
    },
    {
      name = 'doom-one',
      background_mode = 'dark',
      background = '#282c34',
      foreground = '#bbc2cf',
      accents = {
        '#ff6c6b',
        '#81a256',
        '#da8548',
        '#51afef',
        '#c678dd',
        '#46d9ff',
        '#ff8b8b',
      },
    },
    {
      name = 'cool-abyss',
      background_mode = 'dark',
      background = '#0f1923',
      foreground = '#c7d5e0',
      accents = {
        '#4db5bd',
        '#6a9fb5',
        '#8c7cb5',
        '#b56a9f',
        '#bd4d6a',
        '#9aa141',
        '#879a5a',
      },
    },
    {
      name = 'time-traveler',
      background_mode = 'dark',
      background = '#1a1a1a',
      foreground = '#d9d9d9',
      accents = {
        '#ffcc00',
        '#00ccff',
        '#cc00ff',
        '#00d9ad',
        '#ff00cc',
        '#add900',
        '#ff0000',
      },
    },

    {
      name = 'city-lights',
      background_mode = 'dark',
      background = '#1b1f27',
      foreground = '#abb2bf',
      accents = {
        '#61afef',
        '#81a667',
        '#e5c07b',
        '#c678dd',
        '#56b6c2',
        '#e06c75',
        '#be5046',
      },
    },

    {
      name = 'lavender',
      background_mode = 'dark',
      background = '#1e1c31',
      foreground = '#d3d3e7',
      accents = {
        '#b39ddb',
        '#9575cd',
        '#7986cb',
        '#64b5f6',
        '#4fc3f7',
        '#4dd0e1',
        '#419b92',
      },
    },

    {
      name = 'humanoid',
      background_mode = 'dark',
      background = '#1a1a1a',
      foreground = '#e6e6e6',
      accents = {
        '#ff5f87',
        '#ff9f40',
        '#ffd460',
        '#8dc027',
        '#66d9ef',
        '#ae81ff',
        '#f92672',
      },
    },

    {
      name = 'bioluminescence',
      background_mode = 'dark',
      background = '#0f0f1a',
      foreground = '#d9d9e9',
      accents = {
        '#00d9ad',
        '#00ccff',
        '#ff00cc',
        '#cc00ff',
        '#ffcc00',
        '#add900',
        '#ff0066',
      },
    },

    {
      {
        name = 'lavander-forest',
        background_mode = 'dark',
        background = '#1c1e26',
        foreground = '#dcd6f7',
        accents = {
          '#a68bf0',
          '#8be8fc',
          '#57d47a',
          '#cfa6f7',
          '#cdd477',
          '#45d669',
          '#ff6e6e',
        },
      },

      {
        name = 'glow-worm (cyan)',
        background_mode = 'dark',
        background = '#0a1922',
        foreground = '#c3e6f9',
        accents = {
          '#00ffff',
          '#00e6e6',
          '#00cccc',
          '#00b3b3',
          '#009999',
          '#008888',
          '#008888',
        },
      },
    },

    {
      name = 'summer-garden',
      background_mode = 'dark',
      background = '#1f2f16',
      foreground = '#b8c5ab',
      accents = {
        '#f7a278',
        '#f7d66e',
        '#a6d9e8',
        '#f7c6e8',
        '#8be8fc',
        '#97d277',
        '#f78c8c',
      },
    },

    {
      name = 'plastic-dark',
      background_mode = 'dark',
      background = '#1e1e1e',
      foreground = '#e0e0e0',
      accents = {
        '#ff79c6',
        '#8be9fd',
        '#cdd477',
        '#bd93f9',
        '#44d469',
        '#ffb86c',
        '#ff5555',
      },
    },

    {
      name = 'candle-light',
      background_mode = 'dark',
      background = '#1f1f1f',
      foreground = '#f5f5f5',
      accents = {
        '#f7d4a8',
        '#f7bfa8',
        '#f7a8a8',
        '#f7a8c2',
        '#f7a8d9',
        '#f7a8f0',
        '#d4a8f7',
      },
    },
    {
      name = 'mint-edition-dark',
      background_mode = 'dark',
      background = '#1a1f1d',
      foreground = '#a9b5ad',
      accents = {
        '#5e9d7a',
        '#75a88b',
        '#8bb396',
        '#b0bea3',
        '#c6ccb1',
        '#f7f7f7',
        '#ff6f69',
      },
    },
    {
      name = 'magestic-blue-high-contrast',
      background_mode = 'dark',
      background = '#000000',
      foreground = '#ffffff',
      accents = {
        '#007acc',
        '#00bfff',
        '#00d900',
        '#ff00ff',
        '#ff4500',
        '#ffff00',
        '#ff0000',
      },
    },
    {
      name = 'pastel-pink-high-contast',
      background_mode = 'dark',
      background = '#000000',
      foreground = '#ffffff',
      accents = {
        '#ff6b6b',
        '#ffb8b8',
        '#ff9f9f',
        '#ffcccc',
        '#ff7f7f',
        '#ff9999',
        '#ffcccc',
      },
    },
    {
      name = 'Neon Lights',
      background_mode = 'dark',
      background = '#000000',
      foreground = '#ffffff',
      accents = {
        '#ff00ff',
        '#00ffff',
        '#ff0000',
        '#00d900',
        '#ffff00',
        '#ff8000',
        '#8000ff',
      },
    },
    {
      name = 'sinister pastel',
      background_mode = 'dark',
      background = '#2b2b2b',
      foreground = '#e6e6e6',
      accents = {
        '#ff9ac1',
        '#a6e6ff',
        '#ffd580',
        '#c1a6ff',
        '#ffcc99',
        '#98d998',
        '#ff9999',
      },
    },
    {
      name = 'base-16 oceanic',
      background_mode = 'dark',
      background = '#242831',
      foreground = '#edf4ff',
      accents = {
        '#ea7782',
        '#a5c08e',
        '#ffdc97',
        '#adc3d9',
        '#daacd2',
        '#97b6b5',
        '#adc3d9',
      },
    },
    {
      name = 'base-16 oceanic desaturated',
      background_mode = 'dark',
      background = '#1c262b',
      foreground = '#c0c5ce',
      accents = {
        '#bf8b56',
        '#8b9bb0',
        '#a7a7a7',
        '#709191',
        '#6b8ba3',
        '#917091',
        '#919170',
      },
    },
    {
      name = 'darkness-low-contrast',
      background_mode = 'dark',
      background = '#000000',
      foreground = '#d9d9d9',
      accents = {
        '#929292',
        '#929292',
        '#929292',
        '#b5b5b5',
        '#929292',
        '#929292',
        '#a2a2a2',
      },
    },
    {
      name = 'Espresso Elegance',
      background_mode = 'dark',
      background = '#1e1b18',
      foreground = '#d4cfc9',
      accents = {
        '#a67e5d',
        '#c9a66d',
        '#7e9ca6',
        '#b6a67e',
        '#6d7ea6',
        '#a67e8b',
        '#8b7ea6',
      },
    },
    {
      name = 'mystic-glow-blue-dark',
      background_mode = 'dark',
      background = '#111111',
      foreground = '#ccd6f6',
      accents = {
        '#55d9b9',
        '#45aaf2',
        '#cdd477',
        '#a3bffa',
        '#f78c6c',
        '#ff9ac1',
        '#a6c578',
      },
    },
    {
      name = 'pastel-horizon-dark',
      background_mode = 'dark',
      background = '#1D1F21',
      foreground = '#d8d8d8',
      accents = {
        '#ff8b8b',
        '#ffcc8b',
        '#ffe18b',
        '#9cd976',
        '#76d976',
        '#76d9b8',
        '#8b8bff',
      },
    },
    {
      name = 'deep-blue-night',
      background_mode = 'dark',
      background = '#0a0e17',
      foreground = '#c7d5e0',
      accents = {
        '#29537d',
        '#2a6f9e',
        '#3b9ab2',
        '#43968e',
        '#5aa485',
        '#77a37a',
        '#969d6a',
      },
    },
    {
      name = 'lush-planet',
      background_mode = 'dark',
      background = '#1a1f1d',
      foreground = '#b8c5b8',
      accents = {
        '#f7a8b8',
        '#8fd29c',
        '#f7f7a8',
        '#a8b8f7',
        '#f7b8a8',
        '#b8a8f7',
        '#f7d8a8',
      },
    },
  },
  default_palette = 'plastic-dark',
}
