return {
  ai = {
    openai_api_key = os.getenv('OPENAI_API_KEY'),
    gpt_model = 'gpt-4o',
    green_darkening_amount = 0.85,
    auto_darken_greens = true,
    minimum_foreground_contrast = 0.5,
    enable_minimum_foreground_contrast = true,
    temperature = 0.8,
  },

  disable_builtin_schemes = true,

  italic = {
    strings = false,
    comments = false,
    operators = false,
    folds = false,
  },

  hex_palettes = {
    {
      name = '#0E0E0E Onedark',
      background_mode = 'dark',
      background = '#0e0e0e',
      foreground = '#abb2bf',
      accents = {
        '#e06c75',
        '#d19a66',
        '#e5c07b',
        '#81a667',
        '#56b6c2',
        '#61afef',
        '#c678dd',
      },
    },
    {
      name = 'Source Code 1982',
      background_mode = 'dark',
      background = '#0a0f14',
      foreground = '#a7aaa8',
      accents = {
        '#ffcc66',
        '#9aa158',
        '#81a2be',
        '#b294bb',
        '#de935f',
        '#a3685a',
        '#cc6666',
      },
    },
    {
      name = 'Ashes',
      background_mode = 'dark',
      background = '#1B1F22',
      foreground = '#c7ccd1',
      accents = {
        '#aec795',
        '#95c7ae',
        '#c7ae95',
        '#ae95c7',
        '#c795ae',
        '#f7b3b3',
        '#c3707a',
      },
    },
    {
      name = 'Baronesse Garden',
      background_mode = 'dark',
      background = '#1c1c1c',
      foreground = '#f7f7f7',
      accents = {
        '#f7a8b8',
        '#f7d8a8',
        '#f7f7a8',
        '#b8d28f',
        '#8fd29c',
        '#8fd2b8',
        '#a8f7f7',
      },
    },
    {
      name = 'Celestial Rose',
      background_mode = 'dark',
      background = '#181a23',
      foreground = '#cac2ed',
      accents = {
        '#fe99ff',
        '#ffd392',
        '#9cf6ff',
        '#ffb3cc',
        '#88eec5',
        '#ff9292',
        '#fffe91',
      },
    },

    {
      name = 'Moon Garden',
      background_mode = 'dark',
      background = '#0f0f1a',
      foreground = '#8686B3',
      accents = {
        '#a6cfd5',
        '#f7d4b5',
        '#b5d4f7',
        '#f7b5d4',
        '#b4d29a',
        '#d4b5f7',
        '#9ad2b4',
      },
    },
    {
      name = 'City Lights',
      background_mode = 'dark',
      background = '#1b1f27',
      foreground = '#abb2bf',
      accents = {
        '#61afef',
        '#81a667',
        '#e5c07b',
        '#c678dd',
        '#56b6c2',
        '#e06c75',
        '#be5046',
      },
    },
    {
      name = 'Lavender',
      background_mode = 'dark',
      background = '#151925',
      foreground = '#b5b5ed',
      accents = {
        '#d680e2',
        '#93c6b6',
        '#9070d1',
        '#4b9fed',
        '#3cbde8',
        '#32d3a6',
        '#a48fbf',
      },
    },
    {
      name = 'Morning Dew dark',
      background_mode = 'dark',
      background = '#1c1f26',
      foreground = '#c7d5e0',
      accents = {
        '#8cc4c4',
        '#9cb89c',
        '#f0e68c',
        '#b0c4de',
        '#d8bfd8',
        '#f5deb3',
        '#ffb6c1',
      },
    },
    {
      name = 'Night Fall',
      background_mode = 'dark',
      background = '#0d0f12',
      foreground = '#a7aaa8',
      accents = {
        '#56b6c2',
        '#c678dd',
        '#81a667',
        '#e5c07b',
        '#d19a66',
        '#61afef',
        '#e06c75',
      },
    },
    {
      name = 'lush-green',
      background_mode = 'dark',
      background = '#0f1a0e',
      foreground = '#b8c5b4',
      accents = {
        '#419544',
        '#76a63f',
        '#aebb30',
        '#008074',
        '#00bcd4',
        '#3f51b5',
        '#9c27b0',
      },
    },
  },

  default_palette = 'Baronesse Garden',
  -- default_palette = 'Ashes',
  -- default_palette = '#0E0E0E Onedark',
}
